AUT-138 data_upload_endpoints
rcmhunt71/PriceSDK pull request #44
Opened 2020-12-01 15:36 UTC by azayatsfv

GET process_string
POST register_parameter_set
POST upload_data

2020-12-01 17:23 UTC, darkhipenko requested changes
Changes needed

2020-12-01 17:23 UTC, darkhipenko commented on APIs/data_upload/client.py
> +    def process_string(self, loan_number_id, data_language, parameter_set_key, session_id=None, nonce=None,
data_language, parameter_set_key - are optional?

2020-12-01 17:23 UTC, darkhipenko commented on APIs/data_upload/client.py
> +        headers = {"Content-Type": "application/octet-stream", "Accept-Encoding": "deflate, gzip, identity"}
Should be a class attribute, move it outside the method

2020-12-01 17:23 UTC, darkhipenko commented on APIs/data_upload/client.py
> +            params=request_model.as_params_dict, data={}, headers=headers)
data=request_model.payload

2020-12-01 17:23 UTC, darkhipenko commented on APIs/data_upload/client.py
> +    def upload_data(self, token, append, type, session_id=None, nonce=None, payload_dict=None, pretty_print=False):
Move `payload_dict=None` left so it goes after `loan_number_id`

2020-12-01 17:23 UTC, darkhipenko commented on APIs/data_upload/client.py
> +    def register_parameter_set(self, session_id=None, nonce=None, payload_dict=None, pretty_print=False):
Move `payload_dict=None` left so it goes after `self`

2020-12-01 17:23 UTC, darkhipenko commented on APIs/data_upload/client.py
> +        headers = {"Content-Type": "application/x-www-form-urlencoded"}
this is default content-type in PRICE, should be working without providing this line of code

2020-12-01 17:23 UTC, darkhipenko commented on APIs/data_upload/requests/register_parameter_set.py
> +        return args
No need in this class, just use `SimpleRequestModel` class

2020-12-01 17:23 UTC, darkhipenko commented on APIs/data_upload/responses/process_string.py
> +    DATA_LANGUAGE: str = "DataLanguage"
Move to models

2020-12-01 17:23 UTC, darkhipenko commented on APIs/data_upload/responses/upload_data.py
> +    VALID_UNTIL: str = "ValidUntil"
Move to models

2020-12-01 17:23 UTC, darkhipenko commented on APIs/data_upload/responses/register_parameter_set.py
> +    PARAMETER_SET_KEY: str = "ParameterSetKey"
Move to models

2020-12-01 17:58 UTC, azayatsfv commented on APIs/data_upload/client.py
> +    def process_string(self, loan_number_id, data_language, parameter_set_key, session_id=None, nonce=None,
if one of them is used, the second become an optional

2020-12-01 18:29 UTC, azayatsfv commented on APIs/data_upload/requests/register_parameter_set.py
> +        return args
it doesn't work without "payload_dict" as parameter

2020-12-02 16:44 UTC, darkhipenko requested changes
Additional changes needed

2020-12-02 16:44 UTC, darkhipenko commented on APIs/data_upload/client.py
> +    APPLICATION_JSON = "application/octet-stream"
Rename this attribute

2020-12-02 16:44 UTC, darkhipenko commented on APIs/data_upload/client.py
> +    def upload_data(self, token, append, type, payload_dict, session_id=None, nonce=None, pretty_print=False):
`payload_dict=None` ?

2020-12-02 16:44 UTC, darkhipenko commented on APIs/data_upload/client.py
> +    def register_parameter_set(self, payload_dict, session_id=None, nonce=None, pretty_print=False):
`payload_dict=None` ?

2020-12-03 02:59 UTC, darkhipenko approved these changes
Approved

2020-12-03 18:04 UTC, merged