AUT-266_tpo_part2
rcmhunt71/PriceSDK pull request #61
Opened 2020-12-08 21:07 UTC by azayatsfv

GET get_tpo_roles
POST set_tpo_approval_queue_data (Doesn't work. need to be revised after documentation update)

2020-12-08 23:03 UTC, darkhipenko approved these changes
Approved

2020-12-14 23:46 UTC, azayatsfv commented
I have udpated POST set_tpo_approval_queue_data. @darkhipenko Please take a look and make an approve if everything is correct.

2020-12-15 16:59 UTC, darkhipenko requested changes
Please, review request file for `set_tpo_approval_qeue_data`

2020-12-15 16:59 UTC, darkhipenko commented on APIs/tpo/requests/set_tpo_approval_queue_data.py
> +        return payload
Will be inherited from `KwargsRequestModel`, no need in this block of code

2020-12-15 17:51 UTC, darkhipenko approved these changes
Approved

2020-12-15 17:51 UTC, darkhipenko commented on APIs/tpo/requests/set_tpo_approval_queue_data.py
> +        return payload
Resolved, a different key used for building dictionary.

2020-12-15 17:58 UTC, azayatsfv commented on APIs/tpo/requests/set_tpo_approval_queue_data.py
> +                     "FieldNewValue": getattr(self, payload_key.lower())})
DataKey: "FieldNewValue" differ from DataKey ("FieldValue") that used in build_payload method in KwargsRequestModel class

2020-12-15 18:10 UTC, merged