"Adding a loan" calls were moved to creating_loan
rcmhunt71/PriceSDK pull request #95
Opened 2020-12-21 18:38 UTC by azayatsfv

POST add_a_loan
POST import_from_file
POST import_from_file_with_date

2020-12-21 20:32 UTC, darkhipenko requested changes

2020-12-21 20:32 UTC, darkhipenko commented on APIs/creating_loan/requests/import_from_file.py
> +    LOS_FILE = [0, 3]
Better to have a separate attribute for `0` and `3`

2020-12-22 15:49 UTC, azayatsfv commented on APIs/creating_loan/requests/import_from_file.py
> +    LOS_FILE = [0, 3]
fixed

2020-12-22 16:13 UTC, darkhipenko approved these changes
Approved

2020-12-22 17:54 UTC, merged